### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by firdausious** [fritz-c/react-image-lightbox#29]
There is a bug when i use this component on server side rendering

`
[piping] can't execute file: /Users/firdausious/Works/myweb/bin/server.js
[piping] error given was: ReferenceError: window is not defined
   at /Users/firdausious/Works/myweb/node_modules/react-image-lightbox/dist/umd/react-image-lightbox.js:2:1265
   at /Users/firdausious/Works/myweb/node_modules/react-image-lightbox/dist/umd/react-image-lightbox.js:2:1197
   at e.exports (/Users/firdausious/Works/myweb/node_modules/react-image-lightbox/dist/umd/react-image-lightbox.js:2:1483)
   at Object.t.exports (/Users/firdausious/Works/myweb/node_modules/react-image-lightbox/dist/umd/react-image-lightbox.js:2:1959)
   at t (/Users/firdausious/Works/myweb/node_modules/react-image-lightbox/dist/umd/react-image-lightbox.js:1:534)
`

im using react-image-lightbox@3.1.0 with this boiletplate -> https://github.com/erikras/react-redux-universal-hot-example

thanks

**Comment by fritz-c** [comment]
Sorry, react-image-lightbox does not currently support server side rendering (See #27). If you have a bit of experience in the area, though, I would love a pull request that fixes your issue.
